---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hisab-accountmanagement-prod
  name: deployment-account-mgmt-cms
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: account-mgmt-cms
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-mgmt-cms
    spec:
      containers:
        - image: 366374561065.dkr.ecr.ap-south-1.amazonaws.com/account-mgmt-cms-repository:#BUILD_NUMBER
          imagePullPolicy: Always
          name: account-mgmt-cms
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: hisab-accountmanagement-prod
  name: account-mgmt-cms
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: account-mgmt-cms
